// Plain-English names for common ANSI X12 transaction set codes (ST01 / GS01 values).
// Focused on transportation, logistics and last-mile delivery, since that is the
// most common EDI traffic a delivery/dispatch platform receives from clients.
export const TRANSACTION_SET_NAMES = {
  '100': 'Insurance Plan Description',
  '204': 'Motor Carrier Load Tender',
  '210': 'Motor Carrier Freight Details and Invoice',
  '211': 'Motor Carrier Bill of Lading',
  '212': 'Motor Carrier Freight Details and Invoice (Rail)',
  '214': 'Transportation Carrier Shipment Status Message',
  '215': 'Motor Carrier Pickup Manifest',
  '216': 'Motor Carrier Shipment Pickup Notification',
  '217': 'Motor Carrier Loading and Route Guide',
  '219': 'Logistics Service Request',
  '220': 'Logistics Service Response',
  '223': 'Consolidators Freight Bill and Invoice',
  '224': 'Motor Carrier Summary Freight Bill Manifest',
  '225': 'Response to a Motor Carrier Rate Proposal',
  '227': 'Motor Carrier Tariff Information',
  '228': 'Rate Request/Response',
  '240': 'Motor Carrier Package Status',
  '250': 'Purchase Order Shipment Management Document',
  '304': 'Shipping Instructions',
  '309': 'Customs Manifest',
  '310': 'Freight Receipt and Invoice (Ocean)',
  '315': 'Status Details (Ocean)',
  '322': 'Terminal Operations Activity',
  '323': 'Vessel Schedule and Itinerary',
  '350': 'Customs Status Information',
  '353': 'Customs Manifest (Rail)',
  '404': 'Rail Carrier Shipment Information',
  '410': 'Rail Carrier Freight Details and Invoice',
  '412': 'Rail Carrier Waybill Interchange',
  '414': 'Rail Carhire Settlements',
  '417': 'Rail Carrier Waybill Interchange (Advance Consist)',
  '418': 'Rail Advance Interchange Consist',
  '419': 'Advance Car Disposition',
  '420': 'Car Handling Information',
  '421': 'Estimated Time of Arrival and Car Scheduling',
  '423': 'Rail Industrial Switch List',
  '424': 'Rail Carrier Services Settlement',
  '425': 'Rail Waybill Request',
  '426': 'Rail Revenue Waybill',
  '429': 'Railroad Retirement Activity',
  '431': 'Railroad Station Master File',
  '440': 'Shipment Weights',
  '450': 'Railroad Car Management Information',
  '451': 'Railroad Event Report',
  '452': 'Railroad Problem Log Inquiry or Advice',
  '453': 'Railroad Service Commitment Advice',
  '455': 'Railroad Parameter Trace Registration',
  '456': 'Railroad Equipment Inquiry or Advice',
  '460': 'Railroad Price Distribution Request or Response',
  '463': 'Rail Rate Reply',
  '466': 'Rate Request',
  '470': 'Railroad Clearance',
  '475': 'Rail Route File Maintenance',
  '485': 'Rate Reply (Motor)',
  '486': 'Rate Request (Motor)',
  '490': 'Rail Waybill Interchange',
  '492': 'Miscellaneous Rail Reports',
  '494': 'Rail Scale Rates',
  '997': 'Functional Acknowledgment',
  '990': 'Response to a Load Tender',
  '850': 'Purchase Order',
  '855': 'Purchase Order Acknowledgment',
  '856': 'Ship Notice / Manifest (ASN)',
  '860': 'Purchase Order Change Request',
  '810': 'Invoice',
  '820': 'Payment Order / Remittance Advice',
  '832': 'Price / Sales Catalog',
  '846': 'Inventory Inquiry / Advice',
  '870': 'Order Status Report',
  '997A': 'Functional Acknowledgment',
}

export function getTransactionSetName(code) {
  if (!code) return 'Unknown Transaction'
  return TRANSACTION_SET_NAMES[code] || `Unrecognized transaction set (${code})`
}
