// Code lookup tables for the qualifier / code elements that show up over and over
// in EDI segments. These are what actually make a raw EDI file unreadable to a
// newcomer ("N1*ST*..." means nothing until you know ST = Ship To). Each table is
// referenced by name from segmentDictionary.js via an element's `codeSet` property.

export const CODE_SETS = {
  entityIdentifierCode: {
    BT: 'Bill-to Party',
    BY: 'Buying Party (Purchaser)',
    CA: 'Carrier',
    CN: 'Consignee',
    CO: "Company (Party we're doing business with)",
    CS: 'Consolidator',
    DE: 'Delivery Party',
    FR: 'Message From',
    IC: 'Intermediate Consignee',
    MF: 'Manufacturer of Goods',
    PE: 'Payee',
    PR: 'Payer',
    RE: 'Message Receiving Party',
    RI: 'Remit To',
    SE: 'Selling Party',
    SF: 'Ship From',
    ST: 'Ship-to Party',
    SH: 'Shipper',
    SU: 'Supplier/Manufacturer',
    TO: "Message To (Recipient)",
    VN: 'Vendor',
    WH: 'Warehouse',
    '8S': 'Party to Receive Reports',
    Z7: 'Third Party Logistics Provider',
  },
  referenceIdentificationQualifier: {
    '2I': 'Tracking Number',
    '6P': 'Group Number',
    '9V': "Payer's Financial Institution ID",
    AH: 'Agreement Number',
    BM: 'Bill of Lading Number',
    BN: 'Booking Number',
    CN: 'Carrier Shipment/Load ID',
    CO: 'Customer Order Number',
    CT: 'Contract Number',
    DP: 'Department Number',
    EQ: 'Equipment Number',
    IA: 'Internal Vendor Number',
    IN: 'Invoice Number',
    IT: 'Internal Customer Number',
    L1: 'Letter of Credit Number',
    MB: "Master Bill of Lading",
    OQ: 'Order Number (Purchaser)',
    PC: 'Production Code',
    PK: 'Packing List Number',
    PO: 'Purchase Order Number',
    PS: 'Purchasing Order Change Sequence Number',
    QN: 'Quote Number',
    RN: 'Route Number',
    SI: 'Shippers Identifying Number for Shipment (SID)',
    ST: 'Store Number',
    TN: 'Transaction Reference Number / Trip Number',
    VN: 'Vendor Order Number',
    VR: 'Vendor ID Number',
    ZZ: 'Mutually Defined',
  },
  dateTimeQualifier: {
    '001': 'Cancel After',
    '002': 'Delivery Requested',
    '004': 'Purchase Order',
    '010': 'Requested Ship',
    '011': 'Shipped',
    '017': 'Estimated Delivery',
    '035': 'Delivered',
    '037': 'Ship Week Of',
    '050': 'Received',
    '063': 'Pickup Requested',
    '064': 'Pickup Window Start',
    '065': 'Pickup Window End',
    '067': 'Current Schedule Delivery',
    '068': 'Current Schedule Ship',
    '069': 'Delivery Window Start',
    '070': 'Delivery Window End',
    '118': 'Invoice',
    '186': 'Actual Pickup',
    '187': 'Actual Delivery',
    '196': 'Load Start',
    '203': 'Estimated Pickup',
    '253': 'Cancel If Not Delivered By This Date',
    '369': 'Estimated Delivery Window Start',
    '370': 'Estimated Delivery Window End',
    '371': 'Estimated Departure',
    '372': 'Actual Departure',
    '400': 'Estimated Delivery Date/Time',
  },
  unitOrBasisForMeasurementCode: {
    BX: 'Box',
    CA: 'Case',
    CT: 'Carton',
    DZ: 'Dozen',
    EA: 'Each',
    FT: 'Foot',
    G: 'Gram',
    GA: 'Gallon',
    KG: 'Kilogram',
    LB: 'Pound',
    LF: 'Linear Foot',
    PL: 'Pallet/Unit Load',
    PC: 'Piece',
    TN: 'Ton (2000 lb)',
  },
  transportationMethodTypeCode: {
    A: 'Air',
    AC: 'Air Charter',
    AE: 'Air Express',
    AF: 'Air Freight',
    AR: 'Armored Car',
    E: 'Expedited Truck',
    LT: 'Less than Trailer Load (LTL)',
    M: 'Motor (Common Carrier)',
    O: 'Containerized Ocean',
    R: 'Rail',
    RR: 'Rail (Local)',
    S: 'Ocean',
    U: 'Private Parcel Service',
    W: 'Inland Waterway',
  },
  shipmentMethodOfPayment: {
    BP: 'Third Party Pay',
    CC: 'Collect',
    CD: 'Cash on Delivery (COD)',
    DF: 'Defined by Buyer and Seller',
    PB: 'Customer Pickup/Backhaul',
    PC: 'Prepaid but Charged to Customer',
    PD: 'Prepaid by Drop Shipper',
    PL: 'Prepaid Local, Collect Outstate',
    PO: 'Prepaid Only',
    PP: 'Prepaid (by Shipper/Seller)',
    RC: 'Return Collect',
    RS: 'Return Prepaid by Consignee/Buyer',
  },
  purchaseOrderTypeCode: {
    CF: 'Confirmation',
    DS: 'Distribution Order',
    KN: 'Blanket Order',
    NE: 'New Order',
    NR: 'Not Released',
    RL: 'Release or Delivery Order',
    SA: 'Stand-alone Order',
    SP: 'Sample Order',
  },
  productServiceIDQualifier: {
    BP: "Buyer's Part Number",
    IN: 'Buyer Item Number',
    SK: 'SKU',
    UP: 'UPC / EAN',
    VC: "Vendor's (Seller's) Catalog Number",
    VP: "Vendor's (Seller's) Part Number",
  },
  weightQualifier: {
    B: 'Billed Weight',
    G: 'Gross Weight',
    N: 'Net Weight',
    T: 'Tare Weight',
    V: 'Volume',
  },
  ackType997: {
    A: 'Accepted',
    E: 'Accepted, Errors Noted',
    P: 'Partially Accepted',
    R: 'Rejected',
    W: 'Rejected, Content not TR3 compliant',
    X: 'Rejected, Content not within specified range',
  },
  yesNoCondOrResponseCode: {
    Y: 'Yes',
    N: 'No',
  },
}

export function resolveCode(codeSet, value) {
  if (!codeSet || value == null) return null
  const table = CODE_SETS[codeSet]
  if (!table) return null
  return table[String(value).toUpperCase()] || null
}
