// Structural sanity checks that don't require knowing what a segment "means" -
// just whether the file's own internal bookkeeping (control numbers, segment/
// group counts) is self-consistent. Mismatches here usually mean a client's
// EDI file was truncated, hand-edited, or generated by a buggy system - useful
// to surface loudly since they're easy for a non-expert to miss.

function val(el) {
  return Array.isArray(el) ? el.join(':') : el
}

export function validateStructure(parsed) {
  const issues = []
  if (!parsed) return issues

  for (const [icIndex, ic] of parsed.interchanges.entries()) {
    const isaControl = val(ic.isaSegment?.elements[12])
    const ieaControl = val(ic.ieaSegment?.elements[1])
    if (ic.ieaSegment && isaControl !== ieaControl) {
      issues.push({
        level: 'error',
        message: `Interchange ${icIndex + 1}: ISA control number (${isaControl}) does not match IEA control number (${ieaControl}).`,
      })
    }
    if (!ic.ieaSegment) {
      issues.push({ level: 'error', message: `Interchange ${icIndex + 1}: missing its IEA trailer segment.` })
    } else {
      const declaredGroups = Number(val(ic.ieaSegment.elements[0]))
      if (!Number.isNaN(declaredGroups) && declaredGroups !== ic.functionalGroups.length) {
        issues.push({
          level: 'warning',
          message: `Interchange ${icIndex + 1}: IEA says it contains ${declaredGroups} functional group(s), but ${ic.functionalGroups.length} were found.`,
        })
      }
    }

    for (const [grpIndex, grp] of ic.functionalGroups.entries()) {
      const gsControl = val(grp.gsSegment?.elements[5])
      const geControl = val(grp.geSegment?.elements[1])
      const grpLabel = `Interchange ${icIndex + 1}, Functional Group ${grpIndex + 1}`
      if (grp.geSegment && gsControl !== geControl) {
        issues.push({
          level: 'error',
          message: `${grpLabel}: GS control number (${gsControl}) does not match GE control number (${geControl}).`,
        })
      }
      if (!grp.geSegment) {
        issues.push({ level: 'error', message: `${grpLabel}: missing its GE trailer segment.` })
      } else {
        const declaredTxns = Number(val(grp.geSegment.elements[0]))
        if (!Number.isNaN(declaredTxns) && declaredTxns !== grp.transactionSets.length) {
          issues.push({
            level: 'warning',
            message: `${grpLabel}: GE says it contains ${declaredTxns} transaction set(s), but ${grp.transactionSets.length} were found.`,
          })
        }
      }

      for (const [txnIndex, txn] of grp.transactionSets.entries()) {
        const txnLabel = `${grpLabel}, Transaction Set ${txnIndex + 1} (${txn.transactionType || '?'})`
        const stControl = val(txn.stSegment?.elements[1])
        const seControl = val(txn.seSegment?.elements[1])
        if (txn.seSegment && stControl !== seControl) {
          issues.push({
            level: 'error',
            message: `${txnLabel}: ST control number (${stControl}) does not match SE control number (${seControl}).`,
          })
        }
        if (!txn.seSegment) {
          issues.push({ level: 'error', message: `${txnLabel}: missing its SE trailer segment.` })
        } else {
          const declaredCount = Number(val(txn.seSegment.elements[0]))
          const actualCount = txn.segments.length + 2 // + ST + SE
          if (!Number.isNaN(declaredCount) && declaredCount !== actualCount) {
            issues.push({
              level: 'warning',
              message: `${txnLabel}: SE says this transaction set has ${declaredCount} segment(s) (ST through SE), but ${actualCount} were found.`,
            })
          }
        }
      }
    }
  }

  return issues
}
